version: "3.7"
services:
  cumulus_granules_upload:
    image: ghcr.io/unity-sds/unity-data-services:1.5.15
    volumes:
      - /tmp/snpp_upload_test_1:/etc/snpp_upload_test_1
    command: ["upload"]
    environment:
      AWS_ACCESS_KEY_ID: 'dd'
      AWS_SECRET_ACCESS_KEY: 'dddd'
      AWS_SESSION_TOKEN: 'dddd'
      AWS_REGION: 'us-west-2'

      UNITY_BEARER_TOKEN: 'token without the header "Bearer". The alternative is the following group'

      USERNAME: 'plain text | AWS parameter store key | base64 encoded str'
      PASSWORD: 'plain text | AWS parameter store key | base64 encoded str'
      PASSWORD_TYPE: 'PLAIN | PARAM_STORE | BASE64'
      CLIENT_ID: 'ask U-CS. ex: 7a1fglm2d54eoggj13lccivp25'
      COGNITO_URL: 'ask U-CS. ex: https://cognito-idp.us-west-2.amazonaws.com'

      DAPA_API: 'https://k3a3qmarxh.execute-api.us-west-2.amazonaws.com/dev'
      COLLECTION_ID: 'SNDR_SNPP_ATMS_L1A___1'
      STAGING_BUCKET: 'am-uds-dev-cumulus-staging'
      UPLOAD_DIR: '/etc/snpp_upload_test_1'
      PROVIDER_ID: 'SNPP'
      VERIFY_SSL: 'FALSE'
      DELETE_FILES: 'FALSE'
      LOG_LEVEL: '20'
    networks:
      - internal
networks:
  internal: