name: Build PR Merge
on:
  pull_request:
    types: [closed]

env:
  ARTIFACT_BASE_NAME: cumulus_lambda_functions
  PR_NUMBER: github.event.number
  PR_TITLE: github.event.pull_request.title
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - run: |
        artifact_file_name="${{ env.ARTIFACT_BASE_NAME }}-${{ env.software_version }}.zip"
        echo "PR_NUMBER1=${github.event.number}" >> ${GITHUB_ENV}
        echo "PR_TITLE1=${github.event.pull_request.title}" >> ${GITHUB_ENV}
#        PR_NUMBER="${{ github.event.number }}"
#        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "${PR_TITLE} -- ${PR_NUMBER}"
    - run: |
        python3 "${GITHUB_WORKSPACE}/ci.cd/update_setup_version.py" install